{{- if (and .Values.accounting.enabled (not .Values.accounting.external.enabled)) }}
  {{- $mysqlPassword := (randAlphaNum 32 | b64enc) -}}
  {{- $mysqlRootPassword := (randAlphaNum 32 | b64enc) -}}
  {{- if  (lookup "v1" "Secret" .Release.Namespace (printf "%s-mysql" .Release.Name)) }}
    {{- $mysqlPassword = get (lookup "v1" "Secret" .Release.Namespace (printf "%s-mysql" .Release.Name)).data "mysql-password" -}}
    {{- $mysqlRootPassword = get (lookup "v1" "Secret" .Release.Namespace (printf "%s-mysql" .Release.Name)).data "mysql-root-password" -}}
  {{- end}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mysql
  labels:
    {{- include "slurm.labels" . | nindent 4 }}
type: Opaque
data:
  mysql-password: {{ $mysqlPassword }}
  mysql-root-password: {{ $mysqlRootPassword }}
{{- end }}
