{{- if .Values.syncer.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-syncer
    app.kubernetes.io/instance: {{ .Release.Name }}-syncer
    app.kubernetes.io/component: syncer
    {{- include "slurm.labels" . | nindent 4 }}
  name: {{ .Release.Name }}-syncer
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}-syncer
      app.kubernetes.io/instance: {{ .Release.Name }}-syncer
      app.kubernetes.io/component: syncer
      {{- include "slurm.labels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}-syncer
        app.kubernetes.io/instance: {{ .Release.Name }}-syncer
        app.kubernetes.io/component: syncer
        {{- include "slurm.labels" . | nindent 8 }}
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: topology.kubernetes.io/region
                operator: In
                values:
                - {{ .Values.nodeSelector.region }}
              - key: cpu.coreweave.cloud/family
                operator: In
                values:
                  - epyc
      containers:
      - args:
        - --health-probe-bind-address=:8081
        - --metrics-bind-address=127.0.0.1:8080
        - --hooks-api-bind-address=:8000
        - --zap-log-level={{ .Values.syncer.logLevel }}
        - --components
        - syncer
        - --watch-namespace={{ .Release.Namespace }}
        - --slurm-auth-token=$(SLURM_TOKEN)
        - --slurm-api-base=http://{{ .Release.Name }}-rest:6819/
        env:
        - name: SLURM_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-syncer
              key: slurm-token
        command:
        - /manager
        image: "{{ .Values.syncer.image.repository }}:{{ default (print "v" .Chart.Version ) .Values.syncer.image.tag }}"
        ports:
        - containerPort: 8000
          name: hooksapi
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        name: syncer
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: "2"
            memory: 500Mi
          requests:
            cpu: 200m
            memory: 500Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: {{ .Release.Name }}-syncer
      terminationGracePeriodSeconds: 10
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
