apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-ssh-host-keys
  labels:
    {{- include "slurm.labels" . | nindent 4 }}
spec:
  storageClassName: shared-nvme-{{ (lower .Values.nodeSelector.region) }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
