{{- if empty .Values.jwt.existingSecret -}}
{{- if not (lookup "v1" "Secret" .Release.Namespace (include "slurm.jwt.secretName" .)) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "slurm.jwt.secretName" . }}
  labels:
    {{- include "slurm.labels" . | nindent 4 }}
type: Opaque
data:
  jwt.key: {{ randAscii 32 | b64enc | quote }}
{{- else -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "slurm.jwt.secretName" . }}
  labels:
    {{- include "slurm.labels" . | nindent 4 }}
type: Opaque
data:
  jwt.key: {{ get (lookup "v1" "Secret" .Release.Namespace (include "slurm.jwt.secretName" .)).data "jwt.key" }}
{{- end -}}{{/* if not lookup */}}
{{- end -}}{{/* if empty existingSecret*/}}
