{{- if empty .Values.munge.existingSecret -}}
{{- if not (lookup "v1" "Secret" .Release.Namespace (include "slurm.munge.secretName" .)) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "slurm.munge.secretName" . }}
  labels:
    {{- include "slurm.labels" . | nindent 4 }}
type: Opaque
data:
  munge.key: {{ randAlphaNum 1024 | b64enc | quote }}
{{- else -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "slurm.munge.secretName" . }}
  labels:
    {{- include "slurm.labels" . | nindent 4 }}
type: Opaque
data:
  munge.key: {{ get (lookup "v1" "Secret" .Release.Namespace (include "slurm.munge.secretName" .)).data "munge.key" }}
{{- end -}}{{/* if not lookup */}}
{{- end -}}{{/* if empty existingSecret*/}}
