{{- if (include "directories" . ) -}}
{{- if .Values.directoryService.sudoGroups }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Release.Name }}-slurm-sudoers
  labels:
    {{- include "slurm.labels" $ | nindent 4 }}
type: Opaque
stringData:
  10-ldap-sudoers: |-
{{- range .Values.directoryService.sudoGroups }}
    %{{ . }} ALL=(ALL) NOPASSWD: ALL
{{- end }}
---                                                                                                                         
{{- end }}
{{- end -}}