pci4:
  features:
  - pci-4
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: pci.coreweave.cloud/version
              operator: In
              values:
              - '4'
            