apiVersion: v1
kind: Service
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/hostname: {{ .Release.Name }}-login.{{ .Release.Namespace }}.coreweave.cloud
    {{- if .Values.login.service.exposePublicIP }}
    metallb.universe.tf/address-pool: public-{{ .Values.nodeSelector.region | lower }}
    {{- end }}
    {{- if .Values.login.service.annotations }}
    {{- toYaml .Values.login.service.annotations | nindent 4 }}
    {{- end }}
  name: {{ .Release.Name }}-login
  labels:
    {{- include "slurm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.login.service.type }}
  externalTrafficPolicy: {{ .Values.login.service.externalTrafficPolicy }}
  ports:
  - name: ssh
    port: 22
    targetPort: sshd
    protocol: TCP
  selector:
    app.kubernetes.io/name: login
    app.kubernetes.io/instance: {{ .Release.Name }}-login
