apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-slurmctld-state
  labels:
    {{- include "slurm.labels" . | nindent 4 }}
spec:
  storageClassName: block-nvme-{{ (lower .Values.nodeSelector.region) }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 32Gi
