{{ $outer := . }}
{{- range $name, $v := .Values.compute.s6 }}
{{ with $outer }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-s6-service-{{ $name }}
data:
  type: |
    {{ $v.type }}
{{- if eq $v.type "oneshot" }}
  up: |
{{- else }}
  run: |
    #!/command/execlineb -P
{{- end }}
    /etc/s6-overlay/s6-rc.d/{{ $name }}/script.sh start
  script.sh: |
    {{- $v.script | nindent 4 }} 
  base: |
    coreweave
{{- if $v.dependencies }}
{{- range $v.dependencies }}
  {{ . }}: |
    coreweave
{{- end }}
{{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-s6-source-{{ $name }}
data:
  {{ $name }}: |
    coreweave
---
{{- end}}
{{- end}}
{{- range $name, $v := fromYaml (include "slurm.compute.s6" .) }}
{{ with $outer }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-s6-service-{{ $name }}
data:
  type: |
    {{ $v.type }}
{{- if eq $v.type "oneshot" }}
  up: |
{{- else }}
  run: |
    #!/command/execlineb -P
{{- end }}
    /etc/s6-overlay/s6-rc.d/{{ $name }}/script.sh start
  script.sh: |
    {{- $v.script | nindent 4 }} 
  base: |
    coreweave
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-s6-source-{{ $name }}
data:
  {{ $name }}: |
    coreweave
---
{{- end}}
{{- end}}
