{{- if (and .Values.accounting.enabled (not .Values.accounting.external.enabled)) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-slurmdbd-conf
data:
  slurmdbd.conf: |
    ArchiveEvents=yes
    ArchiveJobs=yes
    ArchiveResvs=yes
    ArchiveSteps=no
    ArchiveSuspend=no
    ArchiveTXN=no
    ArchiveUsage=no
    AuthType=auth/munge
    DbdHost={{ .Release.Name }}-accounting
    DbdPort=6819
    DebugLevel=verbose
    PurgeEventAfter=1month
    PurgeJobAfter=12month
    PurgeResvAfter=1month
    PurgeStepAfter=1month
    PurgeSuspendAfter=1month
    PurgeTXNAfter=12month
    PurgeUsageAfter=24month
    SlurmUser=slurm
    LogFile=/dev/null
    PidFile=/var/run/slurmdbd.pid
    StorageLoc={{ .Values.mysql.auth.database }}
    StorageType=accounting_storage/mysql
    StorageUser={{ .Values.mysql.auth.username }}
    StoragePass=$MYSQL_PASSWORD
    StorageHost={{ .Release.Name }}-mysql
    StoragePort=3306
    AuthAltTypes=auth/jwt
    AuthAltParameters=jwt_key={{ include "slurm.jwt.path" . }}
{{- end }}
