a40:
  features:
    - gpu
  resources:
    limits:
      memory: 450Gi
      sunk.coreweave.com/accelerator: "8"
    requests:
      cpu: "80"
      memory: 450Gi
      sunk.coreweave.com/accelerator: "8"

  gresGpu: a40:8

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: gpu.nvidia.com/model
                operator: In
                values:
                  - A40
