apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-rest
  labels:
    {{- include "slurm.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: slurmrestd
    app.kubernetes.io/instance: {{ .Release.Name }}-rest
    app.kubernetes.io/component: "rest"
    {{- include "slurm.labels" . | nindent 4 }}
  ports:
  - name: slurmrestd
    protocol: TCP
    port: 6819
    targetPort: 6819
