apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-compute
  labels:
    {{- include "slurm.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
  - name: sshd
    port: 22
    protocol: TCP
    targetPort: sshd
  selector:
    app.kubernetes.io/name: slurmd
    app.kubernetes.io/component: "compute"
    {{- include "slurm.labels" . | nindent 4 }}
